# Gitlab CI yml file

# This is the major part of the code which explains the stages present in our pipeline.
# In a django application we have various stages which include testing, packing the code,
# performing migrations, collecting static files and running the application.
# The various stages are broadly classified into 3 main categories:

# 1. Test       2. Release      3. Deploy

stages:
- test
- release
# - deploy

variables:
  OMIT_COVERAGE: '*/tests/*,*/tests.py,*/migrations/*,*/urls.py,*/settings.py,*/wsgi.py,manage.py'

# Stage I
# Testing Phase:
# This is where the main code is tested.
# Other options like code coverage, etc are also written in this phase
unit_test:
  stage: test
  # This repo includes python3, pip3
  image: python:3-alpine
  before_script:
    # install requiriment to hubcare_api
    - pip install -r hubcare/hubcare_api/requirements.txt
    - python hubcare/hubcare_api/manage.py makemigrations
    - python hubcare/hubcare_api/manage.py migrate
    # install requiriment to commit metrics
    - pip install -r hubcare/metrics/commit_metrics/requirements.txt
    - python hubcare/metrics/commit_metrics/manage.py makemigrations
    - python hubcare/metrics/commit_metrics/manage.py migrate
    # install requiriment to community metrics
    - pip install -r hubcare/metrics/community_metrics/requirements.txt
    - python hubcare/metrics/community_metrics/manage.py makemigrations
    - python hubcare/metrics/community_metrics/manage.py migrate
    # install requiriment to issue metrics
    - pip install -r hubcare/metrics/issue_metrics/requirements.txt
    - python hubcare/metrics/issue_metrics/manage.py makemigrations
    - python hubcare/metrics/issue_metrics/manage.py migrate
    # install requiriment to pull_request metrics
    - pip install -r hubcare/metrics/pull_request_metrics/requirements.txt
    - python hubcare/metrics/pull_request_metrics/manage.py makemigrations
    - python hubcare/metrics/pull_request_metrics/manage.py migrate
  script:
    # Command to test our application
    - coverage run --source='.' --omit=$OMIT_COVERAGE hubcare/hubcare_api/manage.py test hubcare/hubcare_api/
    - coverage run --source='.' --omit=$OMIT_COVERAGE --append hubcare/metrics/commit_metrics/manage.py test hubcare/metrics/commit_metrics/
    - coverage run --source='.' --omit=$OMIT_COVERAGE --append hubcare/metrics/community_metrics/manage.py test hubcare/metrics/community_metrics/
    - coverage run --source='.' --omit=$OMIT_COVERAGE --append hubcare/metrics/issue_metrics/manage.py test hubcare/metrics/issue_metrics/
    - coverage run --source='.' --omit=$OMIT_COVERAGE --append hubcare/metrics/pull_request_metrics/manage.py test hubcare/metrics/pull_request_metrics/
    - coverage report
    - coveralls

codestyle:
  stage: test
  # This repo includes python3, pip3
  image: python:3-alpine
  before_script:
    - pip install pycodestyle
  script:
    - pycodestyle .

# Stage II
# Release Phase
# In this phase, we package our code using docker
.release:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  script:
    # Build our image using docker
    - docker build $IMAGEPATH -t registry.gitlab.com/cjjcastro/2019-1-hubcare-api/$DOCKERIMAGE:$DOCKERTAG

    # Configure container registry to push using docker
    - docker login -u "$DOCKERLOGIN" -p "$DOCKERPASSWORD" registry.gitlab.com

    # Push the image using docker
    - docker push registry.gitlab.com/cjjcastro/2019-1-hubcare-api/$DOCKERIMAGE:$DOCKERTAG

    # The tag, only master indicates that whenever code is pushed to master branch,
    # only then run the pipeline

# Release to hubcare api service
release_hubcare_api_production:
  extends: .release
  environment: production_hubcare_api
  only: 
    - 46_refactor_api_architecture

release_hubcare_api_development:
  extends: .release
  environment: development_hubcare_api
  only: 
    - devel

# Release to commit metrics service
release_commit_metrics_production:
  extends: .release
  environment: production_commit_metrics
  only: 
    - 46_refactor_api_architecture

release_commit_metrics_development:
  extends: .release
  environment: development_commit_metrics
  only: 
    - devel

# Release to community metrics service
release_community_metrics_production:
  extends: .release
  environment: production_community_metrics
  only: 
    - 46_refactor_api_architecture

release_community_metrics_development:
  extends: .release
  environment: development_community_metrics
  only: 
    - devel

# Release to issue metrics service
release_issue_metrics_production:
  extends: .release
  environment: production_issue_metrics
  only: 
    - 46_refactor_api_architecture

release_issue_metrics_development:
  extends: .release
  environment: development_issue_metrics
  only: 
    - devel

# Release to pull request metrics service
release_pull_request_metrics_production:
  extends: .release
  environment: production_pull_request_metrics
  only: 
    - 46_refactor_api_architecture

release_pull_request_metrics_development:
  extends: .release
  environment: development_pull_request_metrics
  only: 
    - devel
