version: '3'

services:
  hubcareapi:
    container_name: hubcareapi 
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate --run-syncdb && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"